=== alex-polosky/EntityEngine/Maps/Global/SETTINGS/scenario.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:this="http://www.w3schools.com">
  <xs:simpleType name="GUID">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        The representation of a GUID, generally the id of an element.
      </xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="\{[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="scenario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="entities">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="entity">
                <xs:complexType mixed="true">
                  <xs:sequence minOccurs="0">
                    <xs:choice maxOccurs="unbounded">
                      <xs:element name="position" maxOccurs="1">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="x" type="xs:int" />
                            <xs:element name="y" type="xs:int" />
                            <xs:element name="z" type="xs:int" />
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                      <xs:element name="respawn" maxOccurs="1">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="timer" type="xs:unsignedInt" />
                            <xs:element name="kill" type="xs:boolean" />
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
                    </xs:choice>
                  </xs:sequence>
                  <xs:attribute name="guid" type="GUID" use="required" />
                  <xs:attribute name="respawn" type="xs:boolean" use="required" />
                  <xs:attribute name="position" type="xs:boolean" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="wincondition" maxOccurs="1">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="path" type="xs:string" maxOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="guid" type="GUID" use="required" />
      <xs:attribute name="filePath" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alex-polosky/EntityEngine/Maps/Global/SETTINGS/scenario.xml
<?xml version="1.0" encoding="utf-8"?>
<scenario 
  xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com ../../Global/SETTINGS/scenario.xsd"
  guid=""
  filePath="">
  <entities>
    <entity guid="" respawn="false" position="false"/>
    <entity guid="" respawn="true" position="false">
      <respawn>
        <timer>30</timer>
        <kill>false</kill> <!-- kill current obj that is spawned -->
      </respawn>
    </entity>
    <entity guid="" respawn="false" position="true">
      <position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </position>
    </entity>
    <entity guid="" respawn="true" position="true">
      <respawn>
        <timer>60</timer>
        <kill>false</kill><!-- kill current obj that is spawned -->
      </respawn>
      <position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </position>
    </entity>
  </entities>
  <wincondition>
    <path>winConditions.win0</path>
  </wincondition>
</scenario>
